services:
  telegram_translator:
    image: my_telegram_translator:v3
    environment:
      DEEPL_AUTH_KEY: "${DEEPL_AUTH_KEY}"
    container_name: telegram_translator
    # Map container port 8080 to host port 8080 so you can access Flask
    ports:
      - "8080:8080"
    # Restart policy if you want it always running
    restart: unless-stopped
    # Volumes to mount your host files/dirs into the container
    volumes:
      # 1) Mount a local folder into /tmp for logs
      #    e.g. your logs stored in /tmp/telethon_listener.log or /tmp/flask_app.log
      - ./logs:/tmp
      # 2) Mount the messages.db file so your DB persists on the host
      - ./src/messages.db:/app/src/messages.db
      - ./config.yml:/app/config.yml
      - ./channels.yml:/app/channels.yml
      - ./session_name.session:/app/session_name.session

